In [1]:
import pandas as pd
import numpy as np

In [2]:
bond=pd.read_csv('jamesbond.csv')
james=pd.read_csv('jamesbond.csv')

In [3]:
bond

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

## set_index() and reset_index() Method

In [4]:
bond.reset_index(inplace=True)
bond

,index,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [5]:
bond.reset_index(inplace=True)
bond

,level_0,index,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,0,0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,1,1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,2,2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,3,3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,4,4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,5,5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,6,6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,7,7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,8,8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,9,9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,10,10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,11,11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,12,12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,13,13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,14,14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,15,15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,16,16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,17,17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,18,18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,19,19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,20,20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,21,21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,22,22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,23,23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,24,24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,25,25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [6]:
bond.reset_index()

ValueError: cannot insert level_0, already exists

In [7]:
del bond['index']
del bond['level_0']

In [8]:
bond

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [9]:
bond.set_index('Film', inplace=True)
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [10]:
bond.reset_index(inplace=True)

In [11]:
bond

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [12]:
bond.set_index('Film', inplace=True)
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [13]:
bond.reset_index(drop=True)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [14]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

## loc() Method

In [15]:
james.loc[0:10]

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN

In [16]:
bond.sort_index(inplace=True)

In [17]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

#### Selection of rows

In [18]:
bond.loc['Goldfinger':'Live and Let Die']

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN

In [19]:
bond.loc['Thunderball':]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [20]:
bond.loc[:'Diamonds Are Forever']

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8

In [21]:
bond.loc['Casino Royale']

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [22]:
bond.loc[['Casino Royale', 'Moonraker']]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN

In [23]:
bond.loc['Avengers']

KeyError: 'Avengers'

In [ ]:
bond.loc[['Skyfall', 'Avengers']]

#### Selection of columns

In [24]:
bond.loc[:,'Actor']

Film
A View to a Kill                      Roger Moore
Casino Royale                        Daniel Craig
Casino Royale                         David Niven
Diamonds Are Forever                 Sean Connery
Die Another Day                    Pierce Brosnan
Dr. No                               Sean Connery
For Your Eyes Only                    Roger Moore
From Russia with Love                Sean Connery
GoldenEye                          Pierce Brosnan
Goldfinger                           Sean Connery
Licence to Kill                    Timothy Dalton
Live and Let Die                      Roger Moore
Moonraker                             Roger Moore
Never Say Never Again                Sean Connery
Octopussy                             Roger Moore
On Her Majesty's Secret Service    George Lazenby
Quantum of Solace                    Daniel Craig
Skyfall                              Daniel Craig
Spectre                              Daniel Craig
The Living Daylights               Timothy Dalton
The Man with the Golden Gun           Roger Moore
The Spy Who Loved Me                  Roger Moore
The World Is Not Enough            Pierce Brosnan
Thunderball                          Sean Connery
Tomorrow Never Dies                Pierce Brosnan
You Only Live Twice                  Sean Connery
Name: Actor, dtype: object

In [25]:
bond.loc[:, 'Actor':]

,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,
A View to a Kill,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [26]:
bond.loc[:,['Year', 'Budget']]

                                 Year  Budget
Film
A View to a Kill                 1985    54.5
Casino Royale                    2006   145.3
Casino Royale                    1967    85.0
Diamonds Are Forever             1971    34.7
Die Another Day                  2002   154.2
Dr. No                           1962     7.0
For Your Eyes Only               1981    60.2
From Russia with Love            1963    12.6
GoldenEye                        1995    76.9
Goldfinger                       1964    18.6
Licence to Kill                  1989    56.7
Live and Let Die                 1973    30.8
Moonraker                        1979    91.5
Never Say Never Again            1983    86.0
Octopussy                        1983    53.9
On Her Majesty's Secret Service  1969    37.3
Quantum of Solace                2008   181.4
Skyfall                          2012   170.2
Spectre                          2015   206.3
The Living Daylights             1987    68.8
The Man with the Golden Gun      1974    27.7
The Spy Who Loved Me             1977    45.1
The World Is Not Enough          1999   158.3
Thunderball                      1965    41.9
Tomorrow Never Dies              1997   133.9
You Only Live Twice              1967    59.9

#### Selection of rows and column

In [27]:
bond.loc['Casino Royale', 'Year']

Film
Casino Royale    2006
Casino Royale    1967
Name: Year, dtype: int64

In [28]:
bond.loc['Casino Royale':'Moonraker', 'Actor':'Budget']

                                Actor         Director  Box Office  Budget
Film
Casino Royale            Daniel Craig  Martin Campbell       581.5   145.3
Casino Royale             David Niven       Ken Hughes       315.0    85.0
Diamonds Are Forever     Sean Connery     Guy Hamilton       442.5    34.7
Die Another Day        Pierce Brosnan     Lee Tamahori       465.4   154.2
Dr. No                   Sean Connery    Terence Young       448.8     7.0
For Your Eyes Only        Roger Moore        John Glen       449.4    60.2
From Russia with Love    Sean Connery    Terence Young       543.8    12.6
GoldenEye              Pierce Brosnan  Martin Campbell       518.5    76.9
Goldfinger               Sean Connery     Guy Hamilton       820.4    18.6
Licence to Kill        Timothy Dalton        John Glen       250.9    56.7
Live and Let Die          Roger Moore     Guy Hamilton       460.3    30.8
Moonraker                 Roger Moore    Lewis Gilbert       535.0    91.5

In [29]:
bond.reset_index(inplace=True)

In [30]:
bond

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
1,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
2,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
3,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
4,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
5,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
6,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
7,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
8,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
9,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
10,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
11,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
12,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
16,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
17,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
18,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
19,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
20,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
21,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
22,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
23,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
24,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
25,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [31]:
bond.loc[0:10]

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
1,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
2,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
3,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
4,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
5,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
6,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
7,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
8,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
9,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
10,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9

In [32]:
bond.loc[0:5, 'Film': 'Director']

                   Film  Year           Actor         Director
0      A View to a Kill  1985     Roger Moore        John Glen
1         Casino Royale  2006    Daniel Craig  Martin Campbell
2         Casino Royale  1967     David Niven       Ken Hughes
3  Diamonds Are Forever  1971    Sean Connery     Guy Hamilton
4       Die Another Day  2002  Pierce Brosnan     Lee Tamahori
5                Dr. No  1962    Sean Connery    Terence Young

## iloc() Method

In [33]:
bond.loc[15]

Film                 On Her Majesty's Secret Service
Year                                            1969
Actor                                 George Lazenby
Director                               Peter R. Hunt
Box Office                                     291.5
Budget                                          37.3
Bond Actor Salary                                0.6
Name: 15, dtype: object

In [34]:
bond.iloc[15]

Film                 On Her Majesty's Secret Service
Year                                            1969
Actor                                 George Lazenby
Director                               Peter R. Hunt
Box Office                                     291.5
Budget                                          37.3
Bond Actor Salary                                0.6
Name: 15, dtype: object

In [35]:
bond.iloc[[5,10,15,20]]

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
5,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
10,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
15,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
20,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN

In [36]:
bond.iloc[:8]

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
1,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
2,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
3,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
4,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
5,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
6,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
7,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6

In [37]:
bond.iloc[8:]

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
8,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
9,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
10,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
11,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
12,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
16,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
17,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
18,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
19,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
20,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
21,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
22,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
23,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
24,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
25,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [38]:
bond.iloc[4:10, 2:6]

            Actor         Director  Box Office  Budget
4  Pierce Brosnan     Lee Tamahori       465.4   154.2
5    Sean Connery    Terence Young       448.8     7.0
6     Roger Moore        John Glen       449.4    60.2
7    Sean Connery    Terence Young       543.8    12.6
8  Pierce Brosnan  Martin Campbell       518.5    76.9
9    Sean Connery     Guy Hamilton       820.4    18.6

In [39]:
bond.set_index('Film', inplace=True)
bond.sort_index(inplace=True)

In [40]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [41]:
bond.iloc[:8]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6

In [42]:
bond.iloc[8:]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [43]:
bond.iloc[4:10, 2:6]

                              Director  Box Office  Budget  Bond Actor Salary
Film
Die Another Day           Lee Tamahori       465.4   154.2               17.9
Dr. No                   Terence Young       448.8     7.0                0.6
For Your Eyes Only           John Glen       449.4    60.2                NaN
From Russia with Love    Terence Young       543.8    12.6                1.6
GoldenEye              Martin Campbell       518.5    76.9                5.1
Goldfinger                Guy Hamilton       820.4    18.6                3.2

## ix() Method
In pandas version 0.20.0 and above, ix has been disapproved.

## Set new values

#### For a specific cell or row

In [44]:
bond.loc['Dr. No','Actor'] = 'Sir Sean Connery'

In [45]:
bond.loc['Dr. No','Actor']

'Sir Sean Connery'

In [46]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sir Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

#### For multiple columns of same cell

In [47]:
bond.loc['Dr. No', ['Box Office', 'Budget']] = [44880000, 70000000]

In [48]:
bond.loc['Dr. No']

Year                             1962
Actor                Sir Sean Connery
Director                Terence Young
Box Office                  4.488e+07
Budget                          7e+07
Bond Actor Salary                 0.6
Name: Dr. No, dtype: object

In [62]:
bond.loc['Dr. No', ['Box Office', 'Budget']] = [448.8, 7]

#### Set multiple values in Dataframe

In [49]:
mask = bond['Actor'] == 'Sean Connery'

In [50]:
bond[mask]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [51]:
bond.loc[mask, 'Actor'] = 'Sir Sean Connery'

In [52]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sir Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sir Sean Connery,Terence Young,44880000.0,70000000.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sir Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sir Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sir Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sir Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sir Sean Connery,Lewis Gilbert,514.2,59.9,4.4

## Rename Index labels or Columns

#### Using rename() Method

In [53]:
bond.rename(index = {'GoldenEye' : 'Golden Eye'}, columns={'Year' : 'Release Year', 'Box Office' : 'Revenue'}, inplace=True)

In [54]:
bond

,Release Year,Actor,Director,Revenue,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sir Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sir Sean Connery,Terence Young,44880000.0,70000000.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sir Sean Connery,Terence Young,543.8,12.6,1.6
Golden Eye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sir Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sir Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sir Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sir Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [55]:
bond.rename(index = {'Golden Eye' : 'GoldenEye'}, columns={'Release Year' : 'Year', 'Revenue' : 'Box Office' }, inplace=True)

In [56]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sir Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sir Sean Connery,Terence Young,44880000.0,70000000.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sir Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sir Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sir Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sir Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sir Sean Connery,Lewis Gilbert,514.2,59.9,4.4

## nlargest() and nsmallest() Method
Returns the n largest and n smallest values respectively in a column. For a large number of data it"s better to use nlargest() and nsmallest() Method as they are faster than sort_values() Method.

In [57]:
bond.nlargest(n=5, columns='Box Office')

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sir Sean Connery,Terence Young,44880000.0,70000000.0,0.6
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Thunderball,1965,Sir Sean Connery,Terence Young,848.1,41.9,4.7
Goldfinger,1964,Sir Sean Connery,Guy Hamilton,820.4,18.6,3.2
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [58]:
bond['Box Office'].nlargest(7)

Film
Dr. No                   44880000.0
Skyfall                       943.5
Thunderball                   848.1
Goldfinger                    820.4
Spectre                       726.7
Casino Royale                 581.5
From Russia with Love         543.8
Name: Box Office, dtype: float64

In [59]:
bond.nsmallest(n=6, columns='Box Office')

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN

In [60]:
bond['Box Office'].nsmallest()

Film
Licence to Kill                    250.9
A View to a Kill                   275.2
On Her Majesty's Secret Service    291.5
The Living Daylights               313.5
Casino Royale                      315.0
Name: Box Office, dtype: float64

## apply() Method

#### Using apply() on columns

In [64]:
def add_millions(num):
    return str(num) + ' Millions'

In [65]:
bond['Box Office'].apply(add_millions)

Film
A View to a Kill                   275.2 Millions
Casino Royale                      581.5 Millions
Casino Royale                      315.0 Millions
Diamonds Are Forever               442.5 Millions
Die Another Day                    465.4 Millions
Dr. No                             448.8 Millions
For Your Eyes Only                 449.4 Millions
From Russia with Love              543.8 Millions
GoldenEye                          518.5 Millions
Goldfinger                         820.4 Millions
Licence to Kill                    250.9 Millions
Live and Let Die                   460.3 Millions
Moonraker                          535.0 Millions
Never Say Never Again              380.0 Millions
Octopussy                          373.8 Millions
On Her Majesty's Secret Service    291.5 Millions
Quantum of Solace                  514.2 Millions
Skyfall                            943.5 Millions
Spectre                            726.7 Millions
The Living Daylights               313.5 Millions
The Man with the Golden Gun        334.0 Millions
The Spy Who Loved Me               533.0 Millions
The World Is Not Enough            439.5 Millions
Thunderball                        848.1 Millions
Tomorrow Never Dies                463.2 Millions
You Only Live Twice                514.2 Millions
Name: Box Office, dtype: object

#### Using apply() on rows

In [67]:
 def movie_rating(row):
        actor = row[1]
        budget = row[4]
        if actor=='Pierce Brosnan':
            return 'Outstanding'
        elif actor=='Roger Moore' and budget > 40:
            return 'Enjoyable'
        else:
            return 'I have no clue'

In [68]:
bond.apply(movie_rating, axis=1)

Film
A View to a Kill                        Enjoyable
Casino Royale                      I have no clue
Casino Royale                      I have no clue
Diamonds Are Forever               I have no clue
Die Another Day                       Outstanding
Dr. No                             I have no clue
For Your Eyes Only                      Enjoyable
From Russia with Love              I have no clue
GoldenEye                             Outstanding
Goldfinger                         I have no clue
Licence to Kill                    I have no clue
Live and Let Die                   I have no clue
Moonraker                               Enjoyable
Never Say Never Again              I have no clue
Octopussy                               Enjoyable
On Her Majesty's Secret Service    I have no clue
Quantum of Solace                  I have no clue
Skyfall                            I have no clue
Spectre                            I have no clue
The Living Daylights               I have no clue
The Man with the Golden Gun        I have no clue
The Spy Who Loved Me                    Enjoyable
The World Is Not Enough               Outstanding
Thunderball                        I have no clue
Tomorrow Never Dies                   Outstanding
You Only Live Twice                I have no clue
dtype: object